apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: abstractedresourcedefinitions.platform.io
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: platform.io
  # either Namespaced or Cluster
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: abstractedresourcedefinitions
    # singular name to be used as an alias on the CLI and for display
    singular: abstractedresourcedefinition
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: AbstractedResourceDefinition
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
    - ard
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1alpha1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                group:
                  type: string
                scope:
                  type: string
                names:
                  type: object
                  properties:
                    plural:
                      type: string
                    singular:
                      type: string
                    kind:
                      type: string
                    shortNames:
                      type: array
                      items:
                        type: string
                versions:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      served:
                        type: boolean
                      storage:
                        type: boolean
                      schema:
                        description: Schema describes the "fields" that will be accepted by the CRD
                        type: object
                        properties:
                          openAPIV3Schema:
                            description: OpenAPIV3Schema is the OpenAPI v3 schema to use for validation and pruning.
                            type: object
                            x-kubernetes-preserve-unknown-fields: true
                      templates:
                        description: Templates are plain-text Helm templates that will be rendered using the values in the CRD.
                        type: array
                        items:
                          type: object
                          properties:
                            name:
                              type: string
                            template:
                              type: string